# See custom rules in https://github.com/realm/SwiftLint#configuration
identifier_name:
    min_length: 1

excluded:
  - Rickandmortyexample/generated
  - Rickandmortyexample/CharactersQuery.graphql.swift
  - Pods
